### PR TITLE
pull down from upstream git@github.com:LunarG/VulkanSamples.git

### PR DESCRIPTION
**Pull request by ggfan**
* NO local changes*

@bbilodeau @cnorthrop PTAL

### CODE REVIEW

**Comment by cnorthrop** [comment]
We should be able to merge from upstream instead of creating a new commit.

**Comment by ggfan** [comment]
yeah, done with merge and kept the readme file to be specific to this repo. run/debug a few ok:
  draw_cube, spirv-assemble, push_descriptors

**Comment by cnorthrop** [comment]
Nothing jumps out at me as wrong, but that'a big merge.  Maybe do it more often so it is easier to consume. :)

**Comment by ggfan** [comment]
yeah, should do it more often in monthly or quarterly basis.   thx, merging in now.

**Review by bbilodeau — COMMENTED** [review]
LGTM

**Pull request merged**
