### PR TITLE
Sync up with upstream repo git@github.com:LunarG/VulkanSamples.git

### PR DESCRIPTION
**Pull request by ggfan**
@cnorthrop @bbilodeau @hak  May you kindly have a look?
Reason:
  1) This sync-up offers base between upstream and this one.
  2) future bug fixes will go to upstream, and populate to this repo with git merge

### CODE REVIEW

**Comment by ggfan** [comment]
Tested:  pixel C / Android-25 for API-Samples

**Comment by cnorthrop** [comment]
This works for me Gerry, thanks.  There are a few additional files upstream we can add (.gitignore), but otherwise future merges should be pretty easy.  I'll work to get upstream documentation to include more Android details.

**Comment by ggfan** [comment]
Yeah, added .gitignore files, please take another look :-).  The top level .gitignore file could also be consolidated into upstream ( it is mostly android platform related ).  Thank you so much!

**Comment by cnorthrop** [comment]
Here is what I see when I do a test merge from upstream, for future reference.  The conflicts must be worked through, and (I believe) the new files should be dropped.

```
.../vulkan-basic-samples$ git merge trunk
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
CONFLICT (modify/delete): .clang-format deleted in HEAD and modified in trunk. Version trunk of .clang-format left in tree.
Automatic merge failed; fix conflicts and then commit the result.
.../vulkan-basic-samples$ git status
On branch merge_test
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

	new file:   .appveyor.yml
	new file:   .travis.yml
	new file:   API-Samples/android/build.gradle
	new file:   API-Samples/android/gradle.properties
	new file:   API-Samples/android/gradle/wrapper/gradle-wrapper.jar
	new file:   API-Samples/android/gradle/wrapper/gradle-wrapper.properties
	new file:   API-Samples/android/gradlew
	new file:   API-Samples/android/gradlew.bat
	new file:   Utilities/WSIWindow_Sample1/android/app/.gitignore
	new file:   build-android/gradle-templates/local.properties

```

**Comment by ggfan** [comment]
per the discussion, adding files into .gitignore to facilitate future sync-up with upstream

this should solve the problems

**Comment by ggfan** [comment]
Ok, I think it is the good shape to test android studio's import code sample option: to do that, need merge this to the master branch.  Merged it in now, thanks!

**Pull request merged**
